modLoader="javafml"
license="MIT"
loaderVersion="[41,)"

[[mods]]
modId="additionalentityattributes"
displayName="Additional Entity Attributes"
version="${file.jarVersion}"
logoFile="additionalentityattributes.png"
authors=["DaFuqs", "Apace100"]
description='''
Additional Entity Attributes
'''

[[dependencies.additionalentityattributes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"